backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          # Navbar
          - label: "Navbar Brand"
            name: "navbar_brand"
            widget: "string"
            selector: ".js-navbar-brand"
            default: "Cool Sites"

          - label: "Nav Home"
            name: "nav_home"
            widget: "string"
            selector: ".js-nav-home"
            default: "Home"

          - label: "Nav About"
            name: "nav_about"
            widget: "string"
            selector: ".js-nav-about"
            default: "About"

          - label: "Nav Features"
            name: "nav_features"
            widget: "string"
            selector: ".js-nav-features"
            default: "Features"

          - label: "Nav Pricing"
            name: "nav_pricing"
            widget: "string"
            selector: ".js-nav-pricing"
            default: "Pricing"

          - label: "Nav Contact"
            name: "nav_contact"
            widget: "string"
            selector: ".js-nav-contact"
            default: "Contact"

          # Hero Section
          - label: "Hero Title"
            name: "hero_title"
            widget: "string"
            selector: ".js-hero-title"
            default: "Welcome to Cool Sites"

          - label: "Hero Subtitle"
            name: "hero_subtitle"
            widget: "string"
            selector: ".js-hero-subtitle"
            default: "Creating professional, high-quality websites to bring your business online."

          - label: "Hero CTA"
            name: "hero_cta"
            widget: "string"
            selector: ".js-hero-cta"
            default: "Get Started"

          # About Section
          - label: "About Heading"
            name: "about_heading"
            widget: "string"
            selector: ".js-about-heading"
            default: "About Me"

          - label: "About Paragraph"
            name: "about_paragraph"
            widget: "text"
            selector: ".js-about-paragraph"
            default: "Hi, I’m Will, a full-stack developer passionate about creating stunning and functional websites."

          # Features Section
          - label: "Features Heading"
            name: "features_heading"
            widget: "string"
            selector: ".js-features-heading"
            default: "Features"

          - label: "Feature 1 Title"
            name: "feature1_title"
            widget: "string"
            selector: ".js-feature1-title"
            default: "Custom Solutions"

          - label: "Feature 1 Text"
            name: "feature1_text"
            widget: "text"
            selector: ".js-feature1-text"
            default: "Tailored designs to meet your needs."

          - label: "Feature 2 Title"
            name: "feature2_title"
            widget: "string"
            selector: ".js-feature2-title"
            default: "Responsive Design"

          - label: "Feature 2 Text"
            name: "feature2_text"
            widget: "text"
            selector: ".js-feature2-text"
            default: "Websites that look amazing on all devices."

          - label: "Feature 3 Title"
            name: "feature3_title"
            widget: "string"
            selector: ".js-feature3-title"
            default: "Fast Performance"

          - label: "Feature 3 Text"
            name: "feature3_text"
            widget: "text"
            selector: ".js-feature3-text"
            default: "Optimised websites for fast loading speeds."

          # Pricing Section
          - label: "Pricing Heading"
            name: "pricing_heading"
            widget: "string"
            selector: ".js-pricing-heading"
            default: "Pricing"

          - label: "Pricing Description"
            name: "pricing_description"
            widget: "text"
            selector: ".js-pricing-description"
            default: "Choose the plan that suits your needs."

          # Footer
          - label: "Footer Text"
            name: "footer_text"
            widget: "string"
            selector: ".js-footer-text"
            default: "All rights reserved &copy; Cool Sites."



