backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

# Enable Beta features for selector fields
beta_features:
  - ui

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home"
        name: "home"
        fields:
          # Navbar
          - label: "Navbar Brand"
            name: "navbar_brand"
            widget: "string"
            selector: "[data-field='navbar_brand']"

          # Hero Section
          - label: "Hero Title"
            name: "hero_title"
            widget: "string"
            selector: "[data-field='hero_title']"
          - label: "Hero Subtitle"
            name: "hero_subtitle"
            widget: "string"
            selector: "[data-field='hero_subtitle']"
          - label: "Hero CTA"
            name: "hero_cta"
            widget: "string"
            selector: "[data-field='hero_cta']"

          # About Section
          - label: "About Heading"
            name: "about_heading"
            widget: "string"
            selector: "[data-field='about_heading']"
          - label: "About Paragraph 1"
            name: "about_paragraph_1"
            widget: "string"
            selector: "[data-field='about_paragraph_1']"
          - label: "About Paragraph 2"
            name: "about_paragraph_2"
            widget: "string"
            selector: "[data-field='about_paragraph_2']"
          - label: "About Paragraph 3"
            name: "about_paragraph_3"
            widget: "string"
            selector: "[data-field='about_paragraph_3']"

          # Features Section
          - label: "Features Heading"
            name: "features_heading"
            widget: "string"
            selector: "[data-field='features_heading']"
          - label: "Feature 1 Title"
            name: "feature1_title"
            widget: "string"
            selector: "[data-field='feature1_title']"
          - label: "Feature 1 Description"
            name: "feature1_description"
            widget: "text"
            selector: "[data-field='feature1_description']"
          - label: "Feature 2 Title"
            name: "feature2_title"
            widget: "string"
            selector: "[data-field='feature2_title']"
          - label: "Feature 2 Description"
            name: "feature2_description"
            widget: "text"
            selector: "[data-field='feature2_description']"
          - label: "Feature 3 Title"
            name: "feature3_title"
            widget: "string"
            selector: "[data-field='feature3_title']"
          - label: "Feature 3 Description"
            name: "feature3_description"
            widget: "text"
            selector: "[data-field='feature3_description']"

          # Footer
          - label: "Footer Rights"
            name: "footer_rights"
            widget: "string"
            selector: "[data-field='footer_rights']"
          - label: "Footer Trademark"
            name: "footer_trademark"
            widget: "string"
            selector: "[data-field='footer_trademark']"


